import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  Wrapper,
  Title,
  InnerWrapper,
  Button,
  LinkButton,
  Anchor,
  Input,
} from "../styles/Home.styles";

const Home: NextPage = () => {
  return (
    <>
      <Wrapper>
        <Head>
          <title>Demo Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <InnerWrapper>
          <Title>Welcome to Next js World</Title>
        </InnerWrapper>
      </Wrapper>
      <br />
      <Wrapper>
        <InnerWrapper>
          <Button>Normal</Button>
          <Button as="a" href="/">
            Link with button styles
          </Button>
          <LinkButton href="/post/postlist">
            <Anchor> Post List page</Anchor>
          </LinkButton>
          <Input type="text" defaultValue="hello"></Input>
        </InnerWrapper>
      </Wrapper>

      {/* <Link href="/post/postlist">
          <a style={{ textDecoration: "underline" }}>Post List page</a>
        </Link>
        &nbsp;
        <Link href="/weather/citylist">
          <a style={{ textDecoration: "underline" }}>
            Check Weather with City wise
          </a>
        </Link>  */}
    </>
  );
};

export default Home;
